### ISSUE TITLE
Big Sur?

### ISSUE THREAD

**Issue by LeviathanHunter** [AgentRG/swtor_on_mac#14]
Hi, I'm a HUGE fan of your work, mainly because I have been able to play SWTOR on mac for years solely thanks to you. I've tried using this command to install SWTOR on my mac (Big Sur) and terminal says install successful but then the installer won't open, any quick fix? 

Thanks in advance

**Comment by LeviathanHunter** [comment]
Answered myself when I found out Big Sur was basically Catalina on steroids, so there is nothing I can do. 

Thanks anyways and keep up the good work !

**Comment by AgentRG** [comment]
Yep. Regretfully, Big Sur is basically Catalina on steroids. Hopefully one day we will make it finally work with Catalina and others.
